version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: chatapp_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  redis:
    image: redis:7-alpine
    container_name: chatapp_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
